version: "3.7"

services:

  redis:
    image: redis:6.0.9-alpine
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      # - HTTP_USER=root
      # - HTTP_PASSWORD=qwerty
    ports:
      - 9100:8081
    depends_on:
      - redis
  
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass12345
    volumes:
      - C:\applications\web-apps\node-pratice-app\auth-jwt-app\mongodb\database:/data/db
    networks:
      - mongodb_network
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo 10.10.10.60:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
  

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass12345
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    volumes:
      - C:\applications\web-apps\node-pratice-app\auth-jwt-app\mongodb\database
    depends_on:
      - mongodb
    networks:
      - mongodb_network
    ports:
      - 9200:8081
    healthcheck:
      test:  wget --quiet --tries=3 --spider http://admin:admin123@10.10.10.60:8081 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    
volumes:
  redis-data:

networks:
  mongodb_network:
    name: mongodb_network



#reference
# https://markheath.net/post/exploring-redis-with-docker
# https://hackernoon.com/how-to-configurate-redis-redis-commander-docker-616136f2